apiVersion: v1
kind: Service
metadata:
  name: {{ include "silence-web.fullname" . }}
  labels:
    app: {{ include "silence-web.name" . }}
spec:
  type: "{{- if .Values.ingress.enabled }}ClusterIP{{ else }}{{ .Values.service.type }}{{ end }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "silence-web.name" . }}

